'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={location:'Madrid',role:'client'};
const menu=$('#menu'),nav=$('#nav'),result=$('#result'),taskInput=$('#task'),placeInput=$('#place'),modal=$('#appModal'),modalBody=$('#modalBody');
const serviceGroups=[
{name:'Bienestar y cuidado personal',words:['masaje','masajista','relajante','deportivo','bienestar','estetica','estética']},
{name:'Jardín y exterior',words:['jardin','jardín','podar','poda','arbol','árbol','cesped','césped','terraza']},
{name:'Limpieza y organización',words:['limpiar','limpieza','plancha','planchar','orden','organizar']},
{name:'Cuidados y acompañamiento',words:['mayor','mayores','acompañar','acompañamiento','cuidado','cuidados','gestiones']},
{name:'Ayuda física',words:['mudanza','mover','cajas','trastero','cargar','descargar']},
{name:'Profesionales del hogar',words:['fontanero','fontanería','fontaneria','grifo','electricista','electricidad','caldera','aire acondicionado']},
{name:'Hogar y reparaciones',words:['pintar','pintura','mueble','montar','taladro','reparar','arreglo','lampara','lámpara','silicona']},
{name:'Conductor y asistencia',words:['conductor','chofer','chófer','conducir']}];
const classify=v=>{const t=v.toLocaleLowerCase('es');return serviceGroups.find(g=>g.words.some(w=>t.includes(w)))?.name||'Otro servicio'};
function openModal(html){modalBody.innerHTML=html;modal.hidden=false;document.body.classList.add('modal-open');setTimeout(()=>$('.modal-card button,.modal-card input,.modal-card select',modal)?.focus(),0)}
function closeModal(){modal.hidden=true;modalBody.innerHTML='';document.body.classList.remove('modal-open')}
$$('[data-close-modal]').forEach(x=>x.addEventListener('click',closeModal));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!modal.hidden)closeModal()});
menu.addEventListener('click',()=>{const o=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(o));menu.textContent=o?'×':'☰'});$$('a',nav).forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.textContent='☰'}));
$('#searchForm').addEventListener('submit',e=>{e.preventDefault();const task=taskInput.value.trim();if(!task){result.textContent='Cuéntanos con tus propias palabras qué necesitas.';result.classList.add('show');taskInput.focus();return}const category=classify(task),place=placeInput.value.trim()||state.location;result.innerHTML='<span class="match">Categoría sugerida: '+category+'</span><small>Solicitud: “'+escapeHtml(task)+'” · Zona: '+escapeHtml(place)+'. Esta vista previa no envía ni almacena datos.</small>';result.classList.add('show');});
function escapeHtml(v){const d=document.createElement('div');d.textContent=v;return d.innerHTML}
$$('.category[data-task]').forEach(card=>card.addEventListener('click',()=>{taskInput.value=card.dataset.task;setTimeout(()=>taskInput.focus(),0)}));
$('#otherService').addEventListener('click',()=>{taskInput.value='';$('#searchForm').scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>taskInput.focus(),350)});
$('#locationBtn').addEventListener('click',()=>{openModal('<h2 id="modalTitle">Tu zona</h2><p class="lead">Elige una ciudad o escribe tu código postal. No necesitamos tu dirección exacta para buscar.</p><form id="locationForm" class="form-stack"><label>Ciudad o código postal<input id="locationInput" value="'+escapeHtml(state.location)+'" autocomplete="postal-code" required></label><div class="city-grid"><button class="choice" type="button" data-city="Madrid">Madrid</button><button class="choice" type="button" data-city="Barcelona">Barcelona</button><button class="choice" type="button" data-city="Valencia">Valencia</button><button class="choice" type="button" data-city="Sevilla">Sevilla</button></div><button class="primary" type="submit">Usar esta zona</button></form>');$$('[data-city]',modal).forEach(b=>b.addEventListener('click',()=>{$('#locationInput').value=b.dataset.city}));$('#locationForm').addEventListener('submit',e=>{e.preventDefault();state.location=$('#locationInput').value.trim();$('#locationLabel').textContent=state.location;placeInput.value=state.location;closeModal()})});
function auth(kind){const login=kind==='login';openModal('<h2 id="modalTitle">'+(login?'Iniciar sesión':'Crear tu cuenta')+'</h2><p class="lead">'+(login?'Accede a tus solicitudes y conversaciones.':'Elige cómo quieres usar AyudaEnCasa.')+'</p>'+(login?'':'<div class="role-grid"><button class="choice active" type="button" data-role="client"><b>Necesito ayuda</b><br><small>Cuenta de cliente</small></button><button class="choice" type="button" data-role="professional"><b>Ofrezco servicios</b><br><small>Cuenta profesional</small></button></div>')+'<form id="authForm" class="form-stack"><label>Correo electrónico<input type="email" name="email" autocomplete="email" required></label><label>Contraseña<input type="password" name="password" autocomplete="'+(login?'current-password':'new-password')+'" minlength="12" maxlength="128" required></label>'+(!login?'<label><input type="checkbox" required> Acepto las condiciones y la política de privacidad cuando estén publicadas.</label>':'')+'<div class="form-note" id="authNote">'+(login?'La sesión se protege con una cookie segura.':'Usa una contraseña de al menos 12 caracteres.')+'</div><button class="primary" type="submit">'+(login?'Continuar':'Crear cuenta')+'</button>'+(login?'<button type="button" id="forgotPassword">He olvidado mi contraseña</button>':'')+'</form>');if(login)$('#forgotPassword').onclick=forgotPassword;$$('[data-role]',modal).forEach(b=>b.addEventListener('click',()=>{$$('[data-role]',modal).forEach(x=>x.classList.remove('active'));b.classList.add('active');state.role=b.dataset.role}));$('#authForm').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,button=$('button[type="submit"]',form),note=$('#authNote');button.disabled=true;note.textContent='Procesando…';try{const data=Object.fromEntries(new FormData(form));if(!login)data.role=state.role==='professional'?'PROFESSIONAL':'CUSTOMER';const response=await fetch('/api/ayudaencasa/v1/auth/'+(login?'login':'register'),{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify(data)});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||'No se pudo completar la operación.');if(payload.verificationRequired){openModal('<h2 id="modalTitle">Revisa tu correo</h2><p class="lead">Te hemos enviado un enlace para verificar la cuenta antes de iniciar sesión.</p>');return;}state.user=payload.user;closeModal();renderSession();}catch(error){note.textContent=error.message;note.setAttribute('role','alert');}finally{button.disabled=false;}})}
async function loadSession(){try{const r=await fetch('/api/ayudaencasa/v1/me',{credentials:'same-origin'});if(r.ok){const data=await r.json();state.user=data.user;renderSession();}}catch{}}
function renderSession(){if(!state.user)return;$('#login').textContent='Mi cuenta';$('#register').textContent='Salir';loadDashboard()}
$('#login').addEventListener('click',()=>{if(state.user){loadDashboard();$('#accountDashboard')?.scrollIntoView({behavior:'smooth'});}else auth('login')});
$('#register').addEventListener('click',async()=>{if(state.user){await fetch('/api/ayudaencasa/v1/auth/logout',{method:'POST',credentials:'same-origin'});location.reload();}else auth('register')});loadSession();
$('#allCategories').addEventListener('click',()=>{openModal('<h2 id="modalTitle">Todos los servicios</h2><p class="lead">Estas categorías ayudan a descubrir servicios, pero no limitan lo que puedes pedir.</p><div class="category-list">'+[...serviceGroups.map(g=>g.name),'Otro servicio'].map(n=>'<button type="button" data-service="'+escapeHtml(n)+'">'+escapeHtml(n)+'</button>').join('')+'</div>');$$('[data-service]',modal).forEach(b=>b.addEventListener('click',()=>{taskInput.value=b.dataset.service==='Otro servicio'?'': 'Necesito '+b.dataset.service.toLowerCase();closeModal();$('#searchForm').scrollIntoView({behavior:'smooth',block:'center'});taskInput.focus()}))});

async function api(path,options={}){const r=await fetch('/api/ayudaencasa/v1'+path,{credentials:'same-origin',...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'No se pudo completar la operación.');return data}
async function loadDashboard(){
 const panel=$('#accountDashboard'),grid=$('#dashboardGrid');if(!panel||!state.user)return;
 panel.classList.add('show');$('#dashboardTitle').textContent=state.user.role==='PROFESSIONAL'?'Panel profesional':'Panel de cliente';grid.innerHTML='<p class="empty">Cargando…</p>';
 try{if(state.user.role==='PROFESSIONAL')await renderProfessionalDashboard(grid);else await renderCustomerDashboard(grid);await appendJobs(grid)}catch(e){grid.innerHTML='<p class="empty">'+escapeHtml(e.message)+'</p>'}
}
async function renderCustomerDashboard(grid){
 const data=await api('/requests');grid.innerHTML='<article class="dash-card"><h3>Nueva solicitud</h3><form id="requestForm" class="dash-form"><input name="title" placeholder="¿Qué necesitas?" maxlength="120" required><textarea name="description" placeholder="Describe el trabajo" maxlength="3000" required></textarea><select name="categoryId"><option value="">Categoría</option>'+fallbackCategoryOptions()+'</select><input name="location" placeholder="Zona" value="'+escapeHtml(state.location)+'" required><input name="postalPrefix" placeholder="Código postal (opcional)" maxlength="12"><button class="primary" type="submit">Crear y publicar</button><div id="requestNote"></div></form></article><article class="dash-card"><h3>Mis solicitudes</h3><div class="dash-list">'+(data.requests.length?data.requests.map(requestCard).join(''):'<p class="empty">Todavía no tienes solicitudes.</p>')+'</div></article>';
 $('#requestForm').onsubmit=async e=>{e.preventDefault();const note=$('#requestNote'),body=Object.fromEntries(new FormData(e.currentTarget));try{const created=await api('/requests',{method:'POST',body:JSON.stringify(body)});await api('/requests/'+created.request.id+'/publish',{method:'POST'});note.textContent='Solicitud publicada.';await loadDashboard()}catch(err){note.textContent=err.message}};
 $('[data-proposals]',grid).forEach(b=>b.onclick=()=>showProposals(b.dataset.proposals));$('[data-cancel-request]',grid).forEach(b=>b.onclick=async()=>{if(!confirm('¿Cancelar esta solicitud?'))return;try{await api('/requests/'+b.dataset.cancelRequest+'/cancel',{method:'POST'});loadDashboard()}catch(e){alert(e.message)}});
}
function requestCard(r){return '<div class="dash-item"><b>'+escapeHtml(r.title)+'</b><small>'+escapeHtml(r.location_label)+' · <span class="dash-status">'+escapeHtml(r.status)+'</span></small><p>'+escapeHtml(r.description)+'</p>'+(r.status==='PROPOSALS'?'<button type="button" data-proposals="'+r.id+'">Ver propuestas</button>':'')+(['DRAFT','PUBLISHED','MATCHING','PROPOSALS'].includes(r.status)?'<button type="button" data-cancel-request="'+r.id+'">Cancelar solicitud</button>':'')+'</div>'}
async function showProposals(id){try{const data=await api('/requests/'+id+'/proposals');openModal('<h2 id="modalTitle">Propuestas</h2><div class="dash-list">'+(data.proposals.length?data.proposals.map(p=>'<div class="dash-item"><b>'+escapeHtml(p.display_name||'Profesional')+'</b><p>'+escapeHtml(p.message)+'</p><small>'+(p.amount_minor!=null?(p.amount_minor/100).toFixed(2)+' € · ':'')+escapeHtml(p.status)+'</small>'+(p.status==='PENDING'?'<button class="primary" data-accept="'+p.id+'">Aceptar propuesta</button>':'')+'</div>').join(''):'<p class="empty">Aún no hay propuestas.</p>')+'</div>');$$('[data-accept]',modal).forEach(b=>b.onclick=async()=>{await api('/proposals/'+b.dataset.accept+'/accept',{method:'POST'});closeModal();loadDashboard()})}catch(e){alert(e.message)}}
async function renderProfessionalDashboard(grid){
 const [market,profile,services,proposals]=await Promise.all([api('/market/requests'),api('/professional/profile'),api('/professional/services'),api('/proposals')]);
 grid.innerHTML='<article class="dash-card"><h3>Mi perfil profesional</h3><form id="profileForm" class="dash-form"><input name="displayName" placeholder="Nombre público" value="'+escapeHtml(profile.profile?.display_name||'')+'" required><textarea name="bio" placeholder="Experiencia y servicios">'+escapeHtml(profile.profile?.bio||'')+'</textarea><input name="location" placeholder="Zona" value="'+escapeHtml(profile.profile?.location_label||state.location)+'" required><input name="postalPrefix" placeholder="Código postal" value="'+escapeHtml(profile.profile?.postal_prefix||'')+'"><input name="hourlyRate" type="number" min="0" step=".5" placeholder="Tarifa €/hora" value="'+(profile.profile?.hourly_rate_minor!=null?profile.profile.hourly_rate_minor/100:'')+'"><button class="primary" type="submit">Guardar perfil</button><div id="profileNote"></div></form></article><article class="dash-card"><h3>Trabajos disponibles</h3><div class="dash-list">'+(market.requests.length?market.requests.map(marketCard).join(''):'<p class="empty">No hay solicitudes abiertas ahora mismo.</p>')+'</div></article>';
 $('#profileForm').onsubmit=async e=>{e.preventDefault();const x=Object.fromEntries(new FormData(e.currentTarget));x.hourlyRateMinor=x.hourlyRate?Math.round(Number(x.hourlyRate)*100):null;delete x.hourlyRate;try{const selected=[...e.currentTarget.querySelectorAll('[name="service"]:checked')].map(n=>n.value);delete x.service;await api('/professional/profile',{method:'PUT',body:JSON.stringify(x)});await api('/professional/services',{method:'PUT',body:JSON.stringify({categoryIds:selected})});$('#profileNote').textContent='Perfil guardado.'}catch(err){$('#profileNote').textContent=err.message}};
 $('#publishProfile').onclick=async()=>{try{await api('/professional/profile/publish',{method:'POST'});$('#profileNote').textContent='Perfil publicado.'}catch(e){$('#profileNote').textContent=e.message}};$('[data-offer]',grid).forEach(b=>b.onclick=()=>offerModal(b.dataset.offer));
}
function marketCard(r){return '<div class="dash-item"><b>'+escapeHtml(r.title)+'</b><small>'+escapeHtml(r.location_label)+'</small><p>'+escapeHtml(r.description)+'</p><button class="primary" type="button" data-offer="'+r.id+'">Enviar propuesta</button></div>'}
function offerModal(id){openModal('<h2 id="modalTitle">Enviar propuesta</h2><form id="offerForm" class="dash-form"><textarea name="message" maxlength="2000" placeholder="Explica cómo puedes ayudar" required></textarea><input name="amount" type="number" min="0" step=".01" placeholder="Precio propuesto €"><button class="primary">Enviar propuesta</button><div id="offerNote"></div></form>');$('#offerForm').onsubmit=async e=>{e.preventDefault();const x=Object.fromEntries(new FormData(e.currentTarget));const body={message:x.message,amountMinor:x.amount?Math.round(Number(x.amount)*100):null};try{await api('/requests/'+id+'/proposals',{method:'POST',body:JSON.stringify(body)});closeModal();loadDashboard()}catch(err){$('#offerNote').textContent=err.message}}}
function fallbackCategoryOptions(){return serviceGroups.filter(g=>g.name!=='Conductor y asistencia').map(g=>{const ids={'Limpieza y organización':'cleaning','Cuidados y acompañamiento':'care','Jardín y exterior':'garden','Hogar y reparaciones':'repairs','Profesionales del hogar':'trades','Ayuda física':'physical','Bienestar y cuidado personal':'wellbeing'};return '<option value="'+ids[g.name]+'">'+escapeHtml(g.name)+'</option>'}).join('')}
$('#refreshDashboard')?.addEventListener('click',loadDashboard);

async function appendJobs(grid){const data=await api('/jobs');const card=document.createElement('article');card.className='dash-card';card.innerHTML='<h3>Mis trabajos</h3><div class="dash-list">'+(data.jobs.length?data.jobs.map(jobCard).join(''):'<p class="empty">Todavía no hay trabajos asignados.</p>')+'</div>';grid.append(card);$$('[data-chat]',card).forEach(b=>b.onclick=()=>jobChat(b.dataset.chat));$$('[data-start]',card).forEach(b=>b.onclick=async()=>{await api('/jobs/'+b.dataset.start+'/start',{method:'POST'});loadDashboard()});$$('[data-complete]',card).forEach(b=>b.onclick=async()=>{await api('/jobs/'+b.dataset.complete+'/complete',{method:'POST'});loadDashboard()});$('[data-review]',card).forEach(b=>b.onclick=()=>reviewModal(b.dataset.review));$('[data-report-user]',card).forEach(b=>b.onclick=()=>reportModal(b.dataset.reportUser,b.dataset.reportJob));$('[data-block-user]',card).forEach(b=>b.onclick=()=>blockUser(b.dataset.blockUser))}
function jobCard(j){const mine=state.user.id===j.professional_id;let actions='<button type="button" data-chat="'+j.id+'">Chat privado</button>';if(mine&&['AGREED','SCHEDULED'].includes(j.status))actions+='<button class="primary" type="button" data-start="'+j.id+'">Iniciar trabajo</button>';if(!mine&&j.status==='IN_PROGRESS')actions+='<button class="primary" type="button" data-complete="'+j.id+'">Confirmar finalización</button>';if(j.status==='COMPLETED')actions='<button type="button" data-review="'+j.id+'">Valorar servicio</button>';const other=mine?j.customer_id:j.professional_id;actions+='<button type="button" data-report-user="'+other+'" data-report-job="'+j.id+'">Reportar</button><button type="button" data-block-user="'+other+'">Bloquear</button>';return '<div class="dash-item"><b>'+escapeHtml(j.title)+'</b><small>'+escapeHtml(j.location_label)+' · <span class="dash-status">'+escapeHtml(j.status)+'</span></small>'+(j.amount_minor!=null?'<p>Importe acordado: '+(j.amount_minor/100).toFixed(2)+' €</p>':'')+actions+'</div>'}
async function jobChat(id){try{const data=await api('/jobs/'+id+'/messages');openModal('<h2 id="modalTitle">Conversación privada</h2><div class="dash-list" id="chatMessages">'+(data.messages.length?data.messages.map(m=>'<div class="dash-item"><b>'+(m.sender_id===state.user.id?'Tú':'Otra persona')+'</b><p>'+escapeHtml(m.body)+'</p><small>'+escapeHtml(m.created_at)+'</small></div>').join(''):'<p class="empty">Empieza la conversación.</p>')+'</div><form id="chatForm" class="dash-form"><textarea name="body" maxlength="3000" placeholder="Escribe un mensaje" required></textarea><button class="primary">Enviar</button><div id="chatNote"></div></form>');$('#chatForm').onsubmit=async e=>{e.preventDefault();const body=new FormData(e.currentTarget).get('body');try{await api('/jobs/'+id+'/messages',{method:'POST',body:JSON.stringify({body})});jobChat(id)}catch(err){$('#chatNote').textContent=err.message}}}catch(e){alert(e.message)}}
function reviewModal(id){openModal('<h2 id="modalTitle">Valorar el servicio</h2><form id="reviewForm" class="dash-form"><select name="rating" required><option value="">Puntuación</option><option value="5">5 · Excelente</option><option value="4">4 · Muy bien</option><option value="3">3 · Bien</option><option value="2">2 · Mejorable</option><option value="1">1 · Mala experiencia</option></select><textarea name="body" maxlength="2000" placeholder="Cuenta brevemente tu experiencia"></textarea><button class="primary">Publicar valoración</button><div id="reviewNote"></div></form>');$('#reviewForm').onsubmit=async e=>{e.preventDefault();const x=Object.fromEntries(new FormData(e.currentTarget));try{await api('/jobs/'+id+'/review',{method:'POST',body:JSON.stringify({rating:Number(x.rating),body:x.body})});closeModal();loadDashboard()}catch(err){$('#reviewNote').textContent=err.message}}}

function reportModal(userId,jobId){openModal('<h2 id="modalTitle">Reportar un problema</h2><form id="reportForm" class="dash-form"><select name="reason" required><option value="">Motivo</option><option>Comportamiento inapropiado</option><option>Spam o fraude</option><option>Problema con el servicio</option><option>Seguridad</option><option>Otro</option></select><textarea name="details" maxlength="2000" placeholder="Describe qué ha ocurrido"></textarea><button class="primary">Enviar reporte</button><div id="reportNote"></div></form>');$('#reportForm').onsubmit=async e=>{e.preventDefault();const x=Object.fromEntries(new FormData(e.currentTarget));try{await api('/reports',{method:'POST',body:JSON.stringify({subjectUserId:userId,jobId,reason:x.reason,details:x.details})});closeModal();alert('Reporte recibido para revisión.')}catch(err){$('#reportNote').textContent=err.message}}}
async function blockUser(userId){if(!confirm('¿Bloquear a esta persona? El chat dejará de estar disponible.'))return;try{await api('/blocks',{method:'POST',body:JSON.stringify({userId})});alert('Usuario bloqueado.');loadDashboard()}catch(e){alert(e.message)}}

async function handleAuthLinks(){const q=new URLSearchParams(location.search),verify=q.get('verify'),reset=q.get('reset');if(verify){try{await api('/auth/verify-email',{method:'POST',body:JSON.stringify({token:verify})});history.replaceState({},'',location.pathname);openModal('<h2 id="modalTitle">Correo verificado</h2><p class="lead">Tu cuenta ya está activa. Puedes iniciar sesión.</p>')}catch(e){openModal('<h2 id="modalTitle">No se pudo verificar</h2><p class="lead">'+escapeHtml(e.message)+'</p>')}}if(reset){openModal('<h2 id="modalTitle">Nueva contraseña</h2><form id="resetForm" class="dash-form"><input name="password" type="password" minlength="12" maxlength="128" placeholder="Nueva contraseña" required><button class="primary">Cambiar contraseña</button><div id="resetNote"></div></form>');$('#resetForm').onsubmit=async e=>{e.preventDefault();const password=new FormData(e.currentTarget).get('password');try{await api('/auth/password/reset',{method:'POST',body:JSON.stringify({token:reset,password})});history.replaceState({},'',location.pathname);openModal('<h2 id="modalTitle">Contraseña actualizada</h2><p class="lead">Ya puedes iniciar sesión con tu nueva contraseña.</p>')}catch(err){$('#resetNote').textContent=err.message}}}}
function forgotPassword(){openModal('<h2 id="modalTitle">Recuperar contraseña</h2><form id="forgotForm" class="dash-form"><input name="email" type="email" autocomplete="email" placeholder="tu@email.com" required><button class="primary">Enviar instrucciones</button><div id="forgotNote"></div></form>');$('#forgotForm').onsubmit=async e=>{e.preventDefault();const email=new FormData(e.currentTarget).get('email');try{const r=await api('/auth/password/forgot',{method:'POST',body:JSON.stringify({email})});$('#forgotNote').textContent=r.message||'Si la cuenta existe, recibirás instrucciones.'}catch(err){$('#forgotNote').textContent='Si la cuenta existe, recibirás instrucciones.'}}}
handleAuthLinks();

function professionalServiceChecks(selected=[]){const ids={'Limpieza y organización':'cleaning','Cuidados y acompañamiento':'care','Jardín y exterior':'garden','Hogar y reparaciones':'repairs','Profesionales del hogar':'trades','Ayuda física':'physical','Bienestar y cuidado personal':'wellbeing'};return serviceGroups.filter(g=>ids[g.name]).map(g=>'<label><input type="checkbox" name="service" value="'+ids[g.name]+'" '+(selected.includes(ids[g.name])?'checked':'')+'> '+escapeHtml(g.name)+'</label>').join('')}

async function loadPublicProfessionals(){const box=$('#publicProfessionals');if(!box)return;try{const r=await fetch('/api/ayudaencasa/v1/professionals');if(!r.ok)return;const data=await r.json();if(!data.professionals?.length)return;box.innerHTML=data.professionals.map(p=>'<article class="profile"><div><h3>'+escapeHtml(p.display_name)+'</h3><span class="example">PROFESIONAL</span><p>'+escapeHtml(p.bio)+'</p><p>📍 '+escapeHtml(p.location_label)+'</p><p>★ '+Number(p.rating||0).toFixed(1)+' · '+Number(p.review_count||0)+' valoraciones'+(p.hourly_rate_minor!=null?' · desde '+(p.hourly_rate_minor/100).toFixed(2)+' €/h':'')+'</p></div></article>').join('')}catch{}}
loadPublicProfessionals();

function proposalCard(p){return '<div class="dash-item"><b>'+escapeHtml(p.title)+'</b><small>'+escapeHtml(p.location_label)+' · <span class="dash-status">'+escapeHtml(p.status)+'</span></small><p>'+escapeHtml(p.message)+'</p>'+(p.amount_minor!=null?'<p>'+(p.amount_minor/100).toFixed(2)+' €</p>':'')+(p.status==='PENDING'?'<button type="button" data-withdraw="'+p.id+'">Retirar propuesta</button>':'')+'</div>'}
