(() => {
  const posts = [
    { id: 'cyber-route', category: 'ciberseguridad', label: 'Ciberseguridad', time: '8 min', title: 'Mi ruta para llegar a analista junior de ciberseguridad.', excerpt: 'De los fundamentos de red a la investigación de alertas: un plan que convierte el estudio en experiencia demostrable.', lead: 'El objetivo no es memorizar herramientas. Es aprender a ver una señal, hacer buenas preguntas y documentar una respuesta útil.', body: ['Empezar por redes, sistemas operativos y seguridad básica es una inversión que evita aprender ciberseguridad como una lista de comandos. Cada alerta tiene una historia: un origen, un comportamiento y un impacto posible.', 'El plan de trabajo combina el curso Cybersecurity Essentials, práctica segura con Packet Tracer, lectura de logs y simulaciones de un SOC. La idea es construir un portfolio de pequeños casos: qué vi, qué investigué, qué concluí y cómo lo comunicaría a un equipo.', 'Un analista junior no necesita saberlo todo. Necesita observar con método, escalar con criterio y dejar una documentación clara para quien continúe la investigación.'] },
    { id: 'danish-academy', category: 'idiomas', label: 'Idiomas', time: '6 min', title: 'Cómo diseñamos una academia de danés que invita a practicar.', excerpt: 'Voz, escritura, vocabulario inmediato y misiones breves para que estudiar no se sienta como una pantalla interminable.', lead: 'Un idioma entra por el oído, se ordena al escribir y gana vida cuando se usa. La academia tenía que respetar ese ciclo.', body: ['StanNet Danish Academy se diseñó como un aula breve y repetible. Cada misión presenta una situación clara, ofrece audio y deja una pequeña huella escrita. No se trata de pulsar botones: se trata de responder, escuchar de nuevo y volver al contexto.', 'La progresión va de saludos, números y rutinas a conversaciones prácticas, comprensión y redacción. El vocabulario aparece junto a la frase que lo necesita, porque la memoria recuerda mejor las palabras cuando tienen una escena.', 'La siguiente etapa será ampliar las rutas y medir qué ejercicios generan más repetición útil.'] },
    { id: 'english-c2', category: 'idiomas', label: 'Idiomas', time: '7 min', title: 'Una academia de inglés no termina en una lista de verbos.', excerpt: 'La ruta A1-C2 de StanNet English Academy une gramática, pronunciación, escritura y uso real.', lead: 'Saber una regla no es lo mismo que poder usarla en una conversación, un correo o una entrevista.', body: ['La academia está organizada por niveles, pero el nivel es solo el mapa. Cada bloque combina una estructura lingüística, vocabulario útil, escucha, práctica escrita y voz. La meta es tener algo que decir, no solo algo que reconocer.', 'Los verbos frecuentes, los tiempos verbales y los phrasal verbs deben aparecer de forma conectada. Por eso se incorporan dentro de misiones, no como un diccionario aislado.', 'A medida que crece la plataforma, cada módulo se convierte en una pieza de portfolio educativo: una experiencia creada desde la necesidad real de aprender.'] },
    { id: 'music-lab', category: 'ia', label: 'IA + Música', time: '5 min', title: 'Music Lab: escuchar una canción también puede ser estudiar.', excerpt: 'Un experimento para convertir la música en escucha activa, vocabulario y práctica de pronunciación.', lead: 'La música es una puerta magnífica al ritmo de un idioma, pero necesita contexto para transformarse en aprendizaje.', body: ['El laboratorio separa el reproductor del canal musical personal. Allí la idea es trabajar canciones autorizadas o letras aportadas por la persona que aprende, sin mezclar contenido de portfolio con material de estudio.', 'La experiencia ideal sincroniza una letra permitida, destaca palabras relevantes y permite guardar expresiones. Para música comercial, la letra no se puede extraer ni publicar automáticamente por derechos de autor: la plataforma debe trabajar con letras con licencia, de dominio público o proporcionadas por el usuario.', 'Ese límite no debilita el proyecto: lo hace respetuoso, sostenible y técnicamente serio.'] },
    { id: 'portfolio-thinking', category: 'desarrollo', label: 'Desarrollo web', time: '5 min', title: 'Un portfolio no enseña solo resultados. Enseña criterio.', excerpt: 'Cada proyecto de StanNet.Space funciona mejor cuando explica el problema que intenta resolver.', lead: 'Una web profesional no necesita parecerse a todas. Necesita tener una razón para cada decisión.', body: ['El trabajo de diseño parte siempre de la persona que va a usar la web. En una academia, la prioridad es la claridad y el ritmo. En una página de servicios, la confianza. En un portfolio, la narrativa y la evidencia.', 'Los colores, las animaciones y los gráficos no son decoración gratuita. Son herramientas para guiar la mirada y dar personalidad sin impedir la lectura o el uso desde un teléfono.', 'El resultado buscado es una web que tenga carácter y también sea fácil de recorrer.'] },
    { id: 'certificates', category: 'desarrollo', label: 'Portfolio', time: '4 min', title: 'Los certificados dejan de ser archivos perdidos.', excerpt: 'Un visor integrado convierte formación dispersa en evidencia clara, ordenada y fácil de compartir.', lead: 'La formación tiene más valor cuando es encontrable, comprensible y se puede verificar.', body: ['La sección de certificados organiza cada curso por categoría, conserva el PDF original y lo presenta con una ficha clara. Así deja de ser una carpeta de descargas y pasa a formar parte del recorrido profesional.', 'El visor integrado evita que cada visita abra una pestaña nueva. En móvil y ordenador, el visitante puede revisar el documento o descargarlo si lo necesita.', 'La página seguirá creciendo a la vez que lo haga la formación: ciberseguridad, redes, idiomas, programación e inteligencia artificial.'] }
  ];
  const grid = document.querySelector('#blogGrid');
  const search = document.querySelector('#blogSearch');
  const empty = document.querySelector('#blogEmpty');
  const dialog = document.querySelector('#articleDialog');
  const activeFilter = () => document.querySelector('.blog-filter.active')?.dataset.filter || 'all';
  const safe = (value) => String(value).replace(/[&<>"']/g, (char) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[char]));
  function render() {
    const query = search?.value.trim().toLowerCase() || '';
    const list = posts.filter((post) => (activeFilter() === 'all' || post.category === activeFilter()) && `${post.title} ${post.excerpt} ${post.label}`.toLowerCase().includes(query));
    grid.innerHTML = list.map((post) => `<article class="post-card" data-category="${post.category}" data-post="${post.id}" tabindex="0"><span class="post-category">${safe(post.label)} / ${safe(post.time)}</span><h3>${safe(post.title)}</h3><p>${safe(post.excerpt)}</p><button class="text-link" type="button" data-read="${post.id}">Abrir artículo <span>→</span></button></article>`).join('');
    empty.hidden = Boolean(list.length);
  }
  function openArticle(id) {
    const post = posts.find((entry) => entry.id === id); if (!post) return;
    document.querySelector('#articleMeta').textContent = `${post.label.toUpperCase()} · ${post.time.toUpperCase()} DE LECTURA`;
    document.querySelector('#articleTitle').textContent = post.title;
    document.querySelector('#articleLead').textContent = post.lead;
    document.querySelector('#articleBody').innerHTML = post.body.map((paragraph, index) => `${index === 1 ? '<h3>Del concepto a la práctica</h3>' : ''}<p>${safe(paragraph)}</p>`).join('');
    dialog.showModal();
  }
  document.querySelectorAll('.blog-filter').forEach((button) => button.addEventListener('click', () => { document.querySelectorAll('.blog-filter').forEach((item) => item.classList.remove('active')); button.classList.add('active'); render(); }));
  search?.addEventListener('input', render);
  document.addEventListener('click', (event) => { const reader = event.target.closest('[data-read]'); const card = event.target.closest('[data-post]'); if (reader) openArticle(reader.dataset.read); else if (card && !event.target.closest('button')) openArticle(card.dataset.post); });
  document.addEventListener('keydown', (event) => { if (event.key === 'Enter' && event.target.matches('[data-post]')) openArticle(event.target.dataset.post); });
  document.querySelector('.dialog-close')?.addEventListener('click', () => dialog.close());
  document.querySelector('#closeArticle')?.addEventListener('click', () => dialog.close());
  document.querySelector('#postCount').textContent = String(posts.length).padStart(2, '0');
  render();
})();
