document.addEventListener('DOMContentLoaded', () => {
  const weeks = ['Seguridad y trabajo de un SOC','Cómo viaja una conexión','Linux: archivos y permisos','Logs y primera investigación','Usuarios, procesos y servicios','IPv4 y subredes','Wireshark: DNS y TCP','Informe de una captura PCAP','Triage y severidad','Instalar y conocer un SIEM','Autenticación y alertas','Informe de incidente','Inventario autorizado con Nmap','Consultas SQL','Python para leer logs','Extractor de indicadores','Investigar phishing','Eventos Windows y Linux','Hardening y mínimo privilegio','Revisar tres proyectos','Repaso de fundamentos','Simulación de entrevista','CV y presentación del portfolio','Candidaturas y próximos pasos'];
  const lessons = [
    {goal:'Distinguir activo, amenaza, vulnerabilidad y riesgo; explicar cuándo escalar una alerta.',text:'Un activo es algo que necesitas proteger, como una base de datos. Una amenaza es una posible causa de daño. Una vulnerabilidad es una debilidad que podría aprovecharse. El riesgo combina la probabilidad y el impacto del daño: una contraseña débil no implica que ya haya ocurrido un incidente. Confidencialidad significa limitar quién accede; integridad, evitar modificaciones indebidas; disponibilidad, mantener el servicio accesible.',example:'Una alerta de inicio de sesión fallido es una señal para investigar. Comprueba hora, cuenta, origen, número de intentos y si hubo un acceso correcto después. Una persona que olvidó su contraseña puede producir una alerta legítima sin ataque. Un analista documenta hechos, separa hipótesis y escala según el procedimiento del equipo.',lab:'En papel, inventaría cinco activos de tu web. Para cada uno escribe una amenaza, una debilidad, una medida y cómo comprobarías que funciona. No incluyas contraseñas ni datos reales de clientes.',question:'Una alerta muestra cinco contraseñas incorrectas. ¿Qué haces primero?',options:['Confirmo que hay un atacante','Reviso contexto y eventos relacionados','Borro la cuenta'],answer:1,why:'La alerta por sí sola no demuestra un ataque. El contexto permite clasificar y escalar con evidencia.',deliver:'Una tabla de cinco activos y un informe de triage con hechos, hipótesis y siguiente paso.'},
    {goal:'Explicar IP, puertos, DNS, TCP y HTTPS siguiendo una petición web.',text:'La IP identifica una interfaz dentro de una red. Un puerto permite distinguir servicios en un equipo: HTTPS suele usar TCP 443 y SSH TCP 22. DNS resuelve nombres a registros como direcciones IP. TCP establece una conexión y proporciona entrega ordenada; TLS protege la comunicación y autentica el servidor mediante certificados. HTTPS es HTTP sobre TLS. No confundir cifrado con garantía de que una página sea honesta.',example:'Al abrir una web, el equipo busca la dirección del dominio, conecta al servidor y negocia TLS antes de intercambiar HTTP. En TCP, SYN → SYN/ACK → ACK inicia la conexión. Algunos sitios usan HTTP/3 sobre QUIC/UDP, por lo que no todas las conexiones web siguen TCP.',lab:'En tu VM ejecuta los comandos de lectura indicados. Anota qué interfaz tiene IP, qué ruta es la predeterminada y qué código HTTP devuelve tu dominio. No publiques IP privadas ni identificadores personales sin revisarlos.',commands:'ip addr\nip route\nss -tuln\ncurl -I https://www.stannet.space',question:'¿Qué hace DNS al acceder a un dominio?',options:['Traduce el nombre a registros de red','Cifra toda la navegación','Elimina los ataques'],answer:0,why:'DNS consulta registros; TLS se encarga del cifrado de HTTPS.',deliver:'Un diagrama del recorrido navegador → DNS → servidor y explicación de cuatro comandos.'},
    {goal:'Navegar por Linux y comprender permisos sin modificar servicios del sistema.',text:'Linux organiza archivos bajo /. Una ruta absoluta comienza en /; una relativa depende del directorio actual. ls enumera, pwd muestra la ubicación y cd cambia de directorio. Los permisos r, w y x se asignan al propietario, grupo y otros. En un directorio, x permite atravesarlo y w permite modificar sus entradas. Aplica mínimo privilegio: concede solo lo necesario.',example:'chmod 600 notas.txt permite leer y escribir únicamente al propietario. chmod 777 permite a todos leer, escribir y ejecutar; no es una solución general para errores de permisos. El propietario y los permisos deben responder a la necesidad del servicio.',lab:'Crea solo una carpeta de práctica dentro de tu usuario. Ejecuta estos comandos en una VM Linux. Explica el resultado de ls -l antes y después de chmod; no necesitas sudo.',commands:'mkdir -p ~/stannet-lab\ncd ~/stannet-lab\nprintf "Primera evidencia\\n" > notas.txt\nls -l notas.txt\nchmod 600 notas.txt\ncat notas.txt',question:'¿Qué permiso representa 600 para un archivo?',options:['Todos pueden ejecutarlo','Solo el propietario lee y escribe','Nadie puede leerlo'],answer:1,why:'6 equivale a lectura (4) más escritura (2); los ceros no conceden acceso al grupo ni a otros.',deliver:'Un README con entorno, comandos, resultado y explicación del mínimo privilegio.'},
    {goal:'Construir una cronología a partir de eventos y redactar un informe reproducible.',text:'Un log registra eventos, no conclusiones. Identifica fuente, zona horaria, usuario, dirección de origen y resultado. Preserva una copia del material de práctica y diferencia la hora del evento de la hora de recogida. Una IP es un indicador, no la identidad confirmada de una persona. La ausencia de eventos tampoco demuestra ausencia de actividad.',example:'Datos ficticios:\n10:00 usuario=ana origen=192.0.2.10 resultado=fallo\n10:01 usuario=ana origen=192.0.2.10 resultado=fallo\n10:02 usuario=ana origen=192.0.2.10 resultado=correcto\n\nObservación: dos fallos seguidos de un éxito. Hipótesis: contraseña olvidada o acceso indebido. Falta confirmar si el acceso era esperado. Las direcciones de este ejemplo son de documentación.',lab:'Copia estos tres eventos en tu cuaderno. Redacta una cronología, dos hipótesis y tres datos que pedirías. Decide si puedes cerrar el caso con lo disponible y justifica tu respuesta.',question:'¿Qué conclusión permiten estos tres eventos?',options:['Ataque confirmado','Actividad legítima confirmada','Hace falta contexto para clasificar'],answer:2,why:'El patrón justifica investigar; no prueba por sí mismo ni legitimidad ni compromiso.',deliver:'Primer informe: resumen, alcance, evidencia, cronología, hipótesis, limitaciones y siguientes pasos.'}
  ];
  weeks.splice(4, weeks.length - 4, ...(window.stannetCyberCurriculum || []).map(item => item.title));
  lessons.push(...(window.stannetCyberCurriculum || []));
  let saved = {}; let storageAvailable = true;
  try { saved = JSON.parse(localStorage.getItem('stannetCyberV1') || '{}') || {}; } catch { storageAvailable = false; }
  if (typeof saved !== 'object' || Array.isArray(saved)) saved = {};
  saved.notes = saved.notes && typeof saved.notes === 'object' && !Array.isArray(saved.notes) ? saved.notes : {};
  if (saved.curriculumVersion !== 2) {
    saved.previousPlanNotes = Object.entries(saved.notes).filter(([key]) => Number(key) >= 4);
    saved.notes = Object.fromEntries(Object.entries(saved.notes).filter(([key]) => Number(key) < 4));
    saved.curriculumVersion = 2;
  }
  saved.done = Array.isArray(saved.done) ? saved.done.filter(i => Number.isInteger(i) && i >= 0 && i < lessons.length) : [];
  let active = 0;
  const shell = document.createElement('section'); shell.id = 'cyber-classroom'; shell.className = 'cyber-shell';
  shell.innerHTML = `<div class="cyber-layout"><aside class="cyber-panel"><p class="eyebrow">RUTA PRACTICA / SOC JUNIOR</p><label for="cyberMonth">Bloque de estudio</label><select id="cyberMonth">${Array.from({length:Math.ceil(lessons.length / 4)},(_,i)=>`<option value="${i}">Bloque ${i+1}</option>`).join('')}</select><nav class="cyber-menu" aria-label="Semanas" id="cyberWeeks"></nav><p id="cyberProgress"></p><progress class="cyber-progress" id="cyberBar" max="${lessons.length}" value="0"></progress><p>Sesión propuesta: 60 min de teoría, 60 de práctica, 45 de DAW y 15 de repaso. Adapta el ritmo a tu disponibilidad.</p><p>Laboratorios en tu VM o entornos autorizados. La web guía la práctica; no ejecuta comandos en tu equipo.</p></aside><article class="cyber-panel" id="cyberLesson"></article></div>`;
  document.querySelector('main').append(shell);
  const $ = id => document.getElementById(id);
  const persist = () => { try { localStorage.setItem('stannetCyberV1',JSON.stringify(saved)); return true; } catch { storageAvailable = false; return false; } };
  const render = () => {
    const month = Number($('cyberMonth').value);
    $('cyberWeeks').replaceChildren();
    weeks.slice(month*4, month*4+4).forEach((title,i)=>{const n=month*4+i;const b=document.createElement('button');b.textContent=`${saved.done.includes(n)?'✓ ':''}Unidad ${n+1}: ${title}`;b.setAttribute('aria-pressed',String(n===active));b.onclick=()=>{active=n;render();};$('cyberWeeks').append(b);});
    $('cyberProgress').textContent=`${saved.done.length}/${lessons.length} unidades completadas por autoevaluacion.`;$('cyberBar').value=saved.done.length;
    const host=$('cyberLesson');host.replaceChildren();const h=document.createElement('h2');h.textContent=`Unidad ${active+1} · ${weeks[active]}`;host.append(h);
    if(active>=lessons.length){const p=document.createElement('p');p.textContent='Módulo planificado. Las lecciones y pruebas de esta semana todavía no están desarrolladas. Continúa con el primer mes y conserva aquí tus objetivos.';host.append(p);} else {
      const lesson=lessons[active];
      const maps=[['Activo: datos','Debilidad: acceso excesivo','Amenaza: acceso indebido','Control: mínimo privilegio'],['Navegador','DNS: resolver nombre','TCP: conectar','TLS: proteger','HTTP: intercambiar'],['Propietario: rw- (6)','Grupo: --- (0)','Otros: --- (0)'],['Recoger eventos','Ordenar cronología','Contrastar hipótesis','Clasificar y escalar']];
      const diagram=document.createElement('ol');diagram.className='cyber-diagram';diagram.setAttribute('aria-label','Esquema visual de la lección');(lesson.map || maps[active]).forEach(text=>{const item=document.createElement('li');item.textContent=text;diagram.append(item);});host.append(diagram);
      const resource=document.createElement('a');resource.href='https://www.netacad.com/courses/cybersecurity-essentials?courseLang=es-XL';resource.textContent='Complementar con Fundamentos de Ciberseguridad · Cisco Networking Academy';resource.target='_blank';resource.rel='noopener noreferrer';host.append(resource);
      for(const [heading,value] of [['Objetivo',lesson.goal],['Comprende',lesson.text],['Ejemplo explicado',lesson.example],['Práctica',lesson.lab],['Entrega para tu portfolio',lesson.deliver]]){const title=document.createElement('h3');title.textContent=heading;const p=document.createElement('p');p.textContent=value;p.style.whiteSpace='pre-line';host.append(title,p);}
      if(lesson.commands){const pre=document.createElement('pre');pre.textContent=lesson.commands;host.append(pre);}
      const field=document.createElement('fieldset');const legend=document.createElement('legend');legend.textContent=lesson.question;field.append(legend);
      lesson.options.forEach((option,i)=>{const label=document.createElement('label');const input=document.createElement('input');input.type='radio';input.name='cyberAnswer';input.value=i;label.append(input,document.createTextNode(' '+option));field.append(label);});host.append(field);
      const check=document.createElement('button');check.textContent='Comprobar comprensión';const feedback=document.createElement('p');feedback.setAttribute('role','status');
      check.onclick=()=>{const picked=field.querySelector('input:checked');feedback.textContent=!picked?'Selecciona una respuesta.':Number(picked.value)===lesson.answer?'Correcto. '+lesson.why:'Revisa el razonamiento: '+lesson.why;};host.append(check,feedback);
      const solution=document.createElement('details');
      const summary=document.createElement('summary');summary.textContent='Comparar con la solucion razonada';
      const explanation=document.createElement('p');explanation.textContent=lesson.why;
      const rubric=document.createElement('p');rubric.textContent='Autoevaluacion: ¿cite evidencias concretas, separe hechos de hipotesis, respete el alcance autorizado y explique que falta? La respuesta escrita no se puntua automaticamente.';
      solution.append(summary,explanation,rubric);host.append(solution);
    }
    const label=document.createElement('label');label.htmlFor='cyberNotes';label.textContent='Mi cuaderno: qué hice, qué observé y qué debo repasar';const notes=document.createElement('textarea');notes.id='cyberNotes';notes.value=typeof saved.notes[active]==='string'?saved.notes[active]:'';host.append(label,notes);
    const state=document.createElement('p');state.className='cyber-status';state.setAttribute('role','status');state.textContent=storageAvailable?'Guardado local en este navegador. Exporta una copia para conservar tus evidencias.':'El guardado local no está disponible. Exporta tus notas antes de salir.';
    notes.oninput=()=>{saved.notes[active]=notes.value;state.textContent=persist()?'Notas guardadas en este navegador.':'No se pudo guardar. Exporta una copia.';};
    const actions=document.createElement('div');actions.className='cyber-actions';
    if(active<lessons.length){const done=document.createElement('button');done.textContent=saved.done.includes(active)?'Reabrir unidad':'Marcar práctica y entrega completadas';done.onclick=()=>{if(!saved.done.includes(active)&&!notes.value.trim()){state.textContent='Documenta primero tu práctica en el cuaderno.';return;}saved.done=saved.done.includes(active)?saved.done.filter(n=>n!==active):[...saved.done,active];persist();render();};actions.append(done);}
    const exportButton=document.createElement('button');exportButton.textContent='Exportar cuaderno (.md)';exportButton.onclick=()=>{const archive=Array.isArray(saved.previousPlanNotes)?saved.previousPlanNotes.map(([i,note])=>`## Plan anterior: semana ${Number(i)+1}\n${note}\n`).join('\n'):'';const text='# StanNet Cyber Defense Academy\n\n'+weeks.map((w,i)=>`## Unidad ${i+1}: ${w}\nEstado: ${saved.done.includes(i)?'Completada por el alumno':'Pendiente'}\n\n${saved.notes[i]||'Sin notas'}\n`).join('\n')+'\n'+archive;const url=URL.createObjectURL(new Blob([text],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='stannet-cyber-cuaderno.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};actions.append(exportButton);host.append(actions,state);
    if (saved.previousPlanNotes?.length) { const notice=document.createElement('p');notice.textContent='Las notas de la planificacion anterior se conservan como anexo al exportar el cuaderno.';host.append(notice); }
    const details=document.createElement('details');details.innerHTML='<summary>Cómo presentar la evidencia</summary><p>Objetivo → entorno → procedimiento → resultados → limitaciones → aprendizaje. Revisa datos personales antes de publicar. En el mes 1 crea tu repositorio Cybersecurity-Lab; en los siguientes meses añade el PCAP, el incidente SIEM y el script defensivo.</p><p>Las fechas son una guía. Completar esta ruta no garantiza empleo: la meta es poder explicar y demostrar tus capacidades en entrevistas.</p>';host.append(details);
  };
  $('cyberMonth').onchange=()=>{active=Number($('cyberMonth').value)*4;render();};render();
  const soc=document.createElement('section');soc.className='cyber-shell';soc.innerHTML=`<div class="cyber-panel"><p class="eyebrow">PANTALLA DE TRABAJO / SIMULACIÓN EDUCATIVA</p><h2>Tu primera guardia SOC</h2><p>Datos ficticios. Esta interfaz representa tareas de un SOC, no una captura de Wazuh o Splunk. Selecciona una alerta, revisa sus eventos y decide el siguiente paso.</p><div class="cyber-layout"><nav id="socQueue" class="cyber-menu" aria-label="Cola de alertas"></nav><article><h3 id="socTitle"></h3><p id="socContext"></p><pre id="socEvents"></pre><label for="socDecision">Decisión de triage</label><select id="socDecision"><option value="">Selecciona una acción</option><option value="investigate">Investigar contexto</option><option value="close">Cerrar con evidencia</option><option value="escalate">Escalar según playbook</option></select><label for="socReason">Justificación y evidencia</label><textarea id="socReason" placeholder="Indica los eventos relevantes, qué falta confirmar y el siguiente paso."></textarea><button id="socCheck">Revisar mi decisión</button><p id="socFeedback" role="status"></p></article></div><details><summary>Cómo leer esta pantalla</summary><p>Severidad: prioridad inicial de la regla, no prueba de ataque. Host: equipo que produjo el evento. Usuario: cuenta afectada. Origen: dirección observada. Resultado: éxito o fallo. Antes de cerrar o escalar, documenta el alcance, la evidencia y tus dudas. Las herramientas y procedimientos varían entre empresas.</p></details></div>`;shell.after(soc);
  const cases=[
    {title:'AUTH-101 · Fallos de autenticación · Media',context:'Host: linux-lab · Cuenta: ana · Fuente: autenticación · Horas UTC. No sabemos si el acceso era esperado.',events:'10:00:00 login failed user=ana src=192.0.2.10\n10:01:00 login failed user=ana src=192.0.2.10\n10:02:00 login success user=ana src=192.0.2.10',decision:'investigate',explanation:'Investiga si el acceso era esperado, la actividad posterior y otros equipos afectados. Dos fallos y un éxito no prueban compromiso.'},
    {title:'ENDPOINT-202 · Ejecución sospechosa · Alta',context:'Host: workstation-lab · El usuario confirma que abrió un adjunto desconocido. El equipo de respuesta debe investigar según el playbook; SOC L1 no tiene autorización de aislamiento en este ejercicio.',events:'11:14:00 attachment opened user=demo\n11:14:04 document spawned powershell.exe\n11:14:06 outbound connection dst=198.51.100.20\n11:15:00 user reports unexpected window',decision:'escalate',explanation:'Escala con cronología y evidencias correlacionadas. La combinación requiere respuesta prioritaria. No atribuyas una familia de malware sin análisis.'},
    {title:'CHANGE-303 · Servicio reiniciado · Baja',context:'Host: web-lab · Cambio CHG-42 aprobado de 12:00 a 12:15 UTC para reiniciar el servicio. Responsable y host coinciden; comprobación posterior satisfactoria.',events:'12:04:00 service stopped actor=admin-lab\n12:04:02 service started actor=admin-lab\n12:05:00 health check status=healthy\n12:06:00 change CHG-42 validated',decision:'close',explanation:'Puedes cerrar documentando CHG-42 y la comprobación. El evento es real y esperado; no toda alerta benigna es un falso positivo.'}
  ];let selected=0;
  const showCase=()=>{const c=cases[selected];$('socTitle').textContent=c.title;$('socContext').textContent=c.context;$('socEvents').textContent=c.events;$('socReason').value='';$('socDecision').value='';$('socFeedback').textContent='';};
  cases.forEach((c,i)=>{const b=document.createElement('button');b.textContent=c.title;b.onclick=()=>{selected=i;showCase();};$('socQueue').append(b);});
  $('socCheck').onclick=()=>{if(!$('socDecision').value||!$('socReason').value.trim()){$('socFeedback').textContent='Elige una acción y documenta tu razonamiento.';return;}$('socFeedback').textContent=($('socDecision').value===cases[selected].decision?'La acción coincide con el escenario. ':'Revisa la acción elegida. ')+cases[selected].explanation+' Tu texto queda para autoevaluación; no se ha puntuado automáticamente.';};showCase();
});
