document.addEventListener('DOMContentLoaded',()=>{
  const player=document.querySelector('.youtube-player iframe'),urlInput=document.querySelector('#youtubeUrl'),load=document.querySelector('#loadYoutube'),status=document.querySelector('#musicStatus'),lyrics=document.querySelector('#lyricsInput'),make=document.querySelector('#makeExercise'),clear=document.querySelector('#clearLyrics'),output=document.querySelector('#exerciseOutput'),vocabulary=document.querySelector('#musicVocabulary'),language=document.querySelector('#musicLanguage');
  if(!player||!urlInput||!load)return; urlInput.value='https://www.youtube.com/watch?v=qFNZXaBcXkA'; urlInput.setAttribute('value',urlInput.value);
  const direct=document.createElement('a');direct.className='youtube-note';direct.target='_blank';direct.rel='noopener noreferrer';direct.textContent='Si YouTube bloquea la inserción, abrir vídeo directamente ↗';player.parentElement.after(direct);
  const css=document.createElement('style');css.textContent='.language-music{background:radial-gradient(circle at 80% 20%,rgba(255,116,189,.12),transparent 28%),linear-gradient(135deg,rgba(16,17,38,.96),rgba(7,12,30,.96))}.music-tools{display:grid;grid-template-columns:1.5fr .5fr;gap:14px;margin-bottom:18px}.music-control,.music-lyrics,.music-result{padding:20px;border:1px solid var(--line);background:rgba(16,17,38,.78)}.music-control label,.music-lyrics label{display:block;color:var(--lime);font:10px "DM Mono",monospace;letter-spacing:.08em;margin-bottom:10px}.music-input-row{display:flex;gap:8px}.music-input-row input{flex:1;min-width:0}.music-input-row button,.music-actions button{min-height:42px;padding:0 14px;border:1px solid var(--pink);background:var(--pink);color:#fff;font:500 10px "DM Mono",monospace;cursor:pointer}.music-status{margin:10px 0 0;color:var(--muted);font:10px "DM Mono",monospace;line-height:1.6}.music-practice-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.music-lyrics textarea{width:100%;box-sizing:border-box;resize:vertical;background:#0e1024;color:var(--ink);border:1px solid var(--line);padding:13px;font:13px/1.6 "DM Mono",monospace}.music-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.music-actions button:not(.music-primary){background:transparent;color:var(--ink);border-color:var(--line)}.music-result h3{margin:7px 0 16px;font-size:27px;letter-spacing:-.05em}.exercise-output{display:grid;gap:10px;color:var(--ink);font-size:15px;line-height:1.7}.exercise-line{padding:12px;border-left:2px solid var(--lime);background:rgba(207,255,79,.06)}.exercise-line strong{color:var(--lime)}.music-vocabulary{display:flex;gap:7px;flex-wrap:wrap;margin-top:18px}.music-vocabulary span{padding:7px 9px;border:1px solid var(--line);color:var(--muted);font:10px "DM Mono",monospace}@media(max-width:780px){.music-tools,.music-practice-grid{grid-template-columns:1fr}}@media(max-width:520px){.music-input-row{display:grid}.music-input-row button{width:100%}}';document.head.append(css);
  const extractId=value=>{const match=value.match(/(?:v=|youtu\.be\/|embed\/|shorts\/)([\w-]{11})/);return match?match[1]:(/^[\w-]{11}$/.test(value.trim())?value.trim():null)};
  load.addEventListener('click',()=>{const id=extractId(urlInput.value);if(!id){status.textContent='No reconozco un enlace o ID de YouTube valido.';return}player.src=`https://www.youtube-nocookie.com/embed/${id}?rel=0&origin=https%3A%2F%2Fwww.stannet.space&widget_referrer=https%3A%2F%2Fwww.stannet.space%2Fpages%2Fmusic.html`;direct.href=`https://www.youtube.com/watch?v=${id}`;status.textContent='Video cargado. Si YouTube bloquea la inserción, usa el enlace directo.'});
  make.addEventListener('click',()=>{const lines=lyrics.value.split(/\n+/).map(x=>x.trim()).filter(Boolean);if(!lines.length){output.textContent='Primero pega o escribe un fragmento autorizado.';vocabulary.innerHTML='';return}const languageName={en:'ingles',da:'danes',es:'español'}[language.value];output.innerHTML=lines.slice(0,8).map((line,index)=>{const words=line.split(/\s+/);const hidden=words.length>3?words.map((word,i)=>i%4===1?'_____':word).join(' '):line;return `<div class="exercise-line"><strong>${index+1}.</strong> ${hidden}<br><small>Idioma: ${languageName} · Escucha y completa</small></div>`}).join('');const words=[...new Set(lines.join(' ').toLowerCase().replace(/[^a-záéíóúüñæøå' ]/gi,'').split(/\s+/).filter(word=>word.length>4))].slice(0,12);vocabulary.innerHTML='<p class="music-status">Palabras para investigar</p>'+words.map(word=>`<span>${word}</span>`).join('');document.querySelector('#lyricsStatus').textContent='Ejercicio creado. Reproduce el video y completa los huecos escuchando.'});
  clear.addEventListener('click',()=>{lyrics.value='';output.textContent='Añade un texto autorizado y crea tu ejercicio.';vocabulary.innerHTML='';document.querySelector('#lyricsStatus').textContent='La plataforma no extrae letras protegidas automáticamente.'});
});

