document.addEventListener('DOMContentLoaded', () => {
  const $ = id => document.getElementById(id);
  let player, request, generation=0, tracks=[], lines=[], current=-1, timer;
  const extract = value => {
    if (/^[\w-]{11}$/.test(value.trim())) return value.trim();
    try {const url=new URL(value);if(!['youtube.com','www.youtube.com','m.youtube.com','youtu.be'].includes(url.hostname))return null;const id=url.hostname==='youtu.be'?url.pathname.slice(1):url.searchParams.get('v')||url.pathname.split('/')[2];return /^[\w-]{11}$/.test(id||'')?id:null;}catch{return null;}
  };
  const parse = text => {
    const result=[];const offset=Number(text.match(/\[offset:([+-]?\d+)\]/i)?.[1]||0)/1000;
    for(const row of text.split('\n'))for(const stamp of row.matchAll(/\[(\d+):(\d{2}(?:\.\d+)?)\]/g))result.push({time:Math.max(0,Number(stamp[1])*60+Number(stamp[2])+offset),text:row.replace(/\[[^\]]*\]/g,'').trim()});
    return result.sort((a,b)=>a.time-b.time);
  };
  function vocabulary(text){
    const counts=new Map(),stop=new Set('the and that this with have your from they were what when where there their would could should about into just been dont youre its for are but not you all can her his she him our out was'.split(' '));
    for(const word of text.toLowerCase().match(/[a-z]+(?:'[a-z]+)?/g)||[])if(word.length>3&&!stop.has(word.replaceAll("'",'')))counts.set(word,(counts.get(word)||0)+1);
    $('labVocab').replaceChildren();
    for(const [word,count] of [...counts].sort((a,b)=>b[1]-a[1]).slice(0,24)){const a=document.createElement('a');a.textContent=`${word} · ${count}`;a.href='https://dictionary.cambridge.org/dictionary/english-spanish/'+encodeURIComponent(word);a.target='_blank';a.rel='noopener noreferrer';a.title='Consultar significado en español';$('labVocab').append(a);}
  }
  function render(text,synced){
    lines=synced?parse(text):[];current=-1;$('karaokeLines').replaceChildren();
    const rows=lines.length?lines:text.split('\n').filter(Boolean).map(text=>({text}));
    rows.forEach(line=>{const el=document.createElement(lines.length?'button':'p');el.textContent=line.text||'♪';el.className='karaoke-line';if(lines.length){el.type='button';el.onclick=()=>{player?.seekTo(Math.max(0,line.time-Number($('syncOffset').value||0)),true);player?.playVideo();};}$('karaokeLines').append(el);});
    const plain=rows.map(x=>x.text).join('\n');$('labLyrics').value=plain;vocabulary(plain);$('labOutput').textContent='Crea un ejercicio con la letra cargada.';
  }
  function select(index){const t=tracks[index];if(!t)return;$('trackIdentity').textContent=`${t.artist} · ${t.title} · ${t.album||''}`;render(t.synced||t.plain,!!t.synced);$('labLyricsStatus').textContent=t.instrumental?'Pista identificada como instrumental.':t.synced?'Letra sincronizada. Confirma la versión y ajusta el desfase si hace falta.':'Letra disponible sin tiempos: puedes leerla, pero no tiene sincronización.';}
  async function search(q,id){
    request?.abort();request=new AbortController();const token=++generation;tracks=[];$('trackSelect').replaceChildren();$('trackIdentity').textContent='';render('',false);$('labLyricsStatus').textContent='Buscando letra y tiempos...';
    try{const response=await fetch('/api/lyrics?'+new URLSearchParams(q?{q}:{videoId:id}),{signal:request.signal});const data=await response.json();if(token!==generation)return;if(!response.ok)throw new Error(data.error||'No se pudo consultar el catálogo.');tracks=data.tracks||[];tracks.forEach((t,i)=>$('trackSelect').add(new Option(`${t.artist} · ${t.title} (${Math.round(t.duration)} s)${t.synced?' · sincronizada':''}`,String(i))));if(!tracks.length){$('labLyricsStatus').textContent='No se encontró letra. Busca artista y título, o importa un archivo LRC.';return;}select(0);}catch(error){if(error.name!=='AbortError'&&token===generation)$('labLyricsStatus').textContent=error.message;}
  }
  const ready=new Promise((resolve,reject)=>{if(window.YT?.Player)return resolve();const previous=window.onYouTubeIframeAPIReady;window.onYouTubeIframeAPIReady=()=>{previous?.();resolve();};const script=document.createElement('script');script.src='https://www.youtube.com/iframe_api';script.onerror=()=>reject(new Error('No se pudo conectar con YouTube.'));document.head.append(script);setTimeout(()=>{if(!window.YT?.Player)reject(new Error('YouTube no respondió. Revisa los bloqueadores y recarga.'));},15000);});
  ready.catch(error=>{$('labStatus').textContent=error.message;});
  $('labLoad').onclick=async()=>{const id=extract($('labYoutubeUrl').value);if(!id){$('labStatus').textContent='Introduce un enlace válido de YouTube.';return;}$('labDirect').href='https://www.youtube.com/watch?v='+id;$('labStatus').textContent='Preparando reproductor...';search('',id);try{await ready;if(player){player.cueVideoById(id);$('labStatus').textContent='Vídeo preparado. Pulsa reproducir.';return;}player=new YT.Player('labPlayer',{host:'https://www.youtube-nocookie.com',videoId:id,playerVars:{origin:location.origin,playsinline:1,rel:0},events:{onReady:()=>{$('labStatus').textContent='Pulsa reproducir. La letra seguirá el tiempo del vídeo.';},onError:e=>{$('labStatus').textContent=({101:'El propietario no permite insertar este vídeo.',150:'El propietario no permite insertar este vídeo.',153:'YouTube no recibió la identificación del sitio. Revisa los bloqueadores.',100:'Vídeo no disponible.'})[e.data]||'YouTube no pudo reproducir esta versión. Usa el enlace directo.';},onStateChange:()=>{clearInterval(timer);if(player.getPlayerState()===1)timer=setInterval(tick,200);tick();}}});}catch(error){$('labStatus').textContent=error.message;}};
  function tick(){if(!lines.length||!player?.getCurrentTime)return;const time=player.getCurrentTime()+Number($('syncOffset').value||0);let index=-1;for(let i=0;i<lines.length&&lines[i].time<=time;i++)index=i;if(index===current)return;const rows=$('karaokeLines').children;if(rows[current])rows[current].removeAttribute('aria-current');current=index;if(rows[index]){rows[index].setAttribute('aria-current','true');if($('followLyrics').checked)$('karaokeLines').scrollTop=Math.max(0,rows[index].offsetTop-$('karaokeLines').offsetTop-$('karaokeLines').clientHeight/2);}}
  $('trackSelect').onchange=()=>select(Number($('trackSelect').value));$('lyricsSearch').onclick=()=>{const q=$('trackQuery').value.trim();if(q)search(q);};$('trackQuery').onkeydown=e=>{if(e.key==='Enter')$('lyricsSearch').click();};$('syncOffset').oninput=tick;
  $('lrcFile').onchange=async()=>{const file=$('lrcFile').files[0];if(!file)return;if(file.size>100000){$('labLyricsStatus').textContent='Máximo 100 KB.';return;}request?.abort();const token=++generation;const text=await file.text();if(token!==generation)return;render(text,true);$('trackIdentity').textContent=file.name;$('labLyricsStatus').textContent=lines.length?'Archivo LRC cargado.':'No se encontraron marcas [minuto:segundo].';};
  $('labMake').onclick=()=>{$('labOutput').replaceChildren();const rows=$('labLyrics').value.split('\n').filter(x=>x.trim()).slice(0,12);if(!rows.length){$('labOutput').textContent='Carga primero una letra.';return;}rows.forEach((line,i)=>{const words=line.split(/\s+/),target=words.findIndex(w=>w.replace(/[^a-z]/gi,'').length>3),card=document.createElement('div');card.className='lab-line';if(target<0){card.textContent=line;$('labOutput').append(card);return;}const input=document.createElement('input');input.setAttribute('aria-label',`Palabra que falta en frase ${i+1}`);input.autocomplete='off';card.append(document.createTextNode(words.slice(0,target).join(' ')+' '),input,document.createTextNode(' '+words.slice(target+1).join(' ')));const button=document.createElement('button'),result=document.createElement('span');button.textContent='Comprobar';result.setAttribute('role','status');button.onclick=()=>{const normalize=s=>s.toLowerCase().replace(/[^a-z']/g,'');result.textContent=normalize(input.value)===normalize(words[target])?' Correcto.':' Modelo: '+words[target];};card.append(button,result);$('labOutput').append(card);});vocabulary($('labLyrics').value);};
  $('labClear').onclick=()=>{request?.abort();generation++;tracks=[];$('trackSelect').replaceChildren();$('trackIdentity').textContent='';render('',false);$('labLyricsStatus').textContent='Carga una canción para empezar.';};window.addEventListener('pagehide',()=>{clearInterval(timer);request?.abort();});
  const searchButton=$('youtubeSearchButton'), searchInput=$('youtubeSearch'), results=$('youtubeResults');
  async function youtubeSearch(){const query=searchInput.value.trim();if(!query)return;results.textContent='Buscando vídeos...';try{const response=await fetch('/api/youtube-search?q='+encodeURIComponent(query));const data=await response.json();if(!response.ok)throw new Error(data.error||'No se pudo buscar en YouTube.');results.innerHTML='';(data.results||[]).forEach(video=>{const button=document.createElement('button');button.type='button';button.className='youtube-result';button.innerHTML=`<img src="${video.thumbnail}" alt=""><span><strong>${video.title}</strong><small>${video.channel}</small></span>`;button.onclick=()=>{$('labYoutubeUrl').value='https://www.youtube.com/watch?v='+video.id;$('labLoad').click();};results.append(button);});if(!data.results?.length)results.textContent='No encontramos vídeos insertables para esa búsqueda.';}catch(error){results.textContent=error.message;}}
  searchButton?.addEventListener('click',youtubeSearch);searchInput?.addEventListener('keydown',event=>{if(event.key==='Enter')youtubeSearch();});
  const chordNames=['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'];let chordShift=0;
  function transpose(amount){chordShift+=amount;$('songChords').value=$('songChords').value.replace(/\b([A-G](?:#|b)?)(m|maj7|sus4|sus2|7|dim|aug|add9)?\b/g,(match,note,suffix='')=>{const index=chordNames.indexOf(note.replace('b','#'));return index<0?match:chordNames[(index+chordShift+120)%12]+suffix;});$('keyStatus').textContent=`Transposición ${chordShift>0?'+':''}${chordShift} semitono${Math.abs(chordShift)===1?'':'s'}`;}
  $('transposeUp')?.addEventListener('click',()=>transpose(1));$('transposeDown')?.addEventListener('click',()=>transpose(-1));
});
