/* Menus generales. No sustituyen un plan clínico individualizado. */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.NutriPlan=api})(typeof globalThis!=='undefined'?globalThis:this,function(){
const recipes={
 desayuno:[
 ['Avena con manzana y canela',['avena','manzana','canela']],['Tostadas con huevo y tomate',['pan integral','huevo','tomate']],['Yogur natural con frutos rojos y avena',['yogur natural','frutos rojos','avena']],['Tortilla con espinacas y pan integral',['huevo','espinacas','pan integral']],['Porridge de pera y semillas',['avena','pera','semillas']],['Pan integral con aguacate y tomate',['pan integral','aguacate','tomate']],['Yogur natural con plátano y semillas',['yogur natural','plátano','semillas']],['Revuelto de champiñones y tostada',['huevo','champiñones','pan integral']],['Avena con fresas y nueces',['avena','fresas','nueces']],['Tostada de queso fresco y pepino',['pan integral','queso fresco','pepino']]],
 comida:[
 ['Pollo al horno con arroz y brócoli',['pollo','arroz','brócoli']],['Lentejas con verduras y arroz',['lentejas','zanahoria','arroz']],['Merluza con patata y ensalada',['merluza','patata','lechuga','tomate']],['Ensalada templada de garbanzos y calabacín',['garbanzos','calabacín','tomate']],['Pavo salteado con quinoa y pimiento',['pavo','quinoa','pimiento']],['Pasta integral con tomate y atún',['pasta integral','tomate','atún']],['Pollo con cuscús y zanahoria',['pollo','cuscús','zanahoria']],['Alubias con verduras y huevo',['alubias','zanahoria','huevo']],['Salmón con boniato y judías verdes',['salmón','boniato','judías verdes']],['Arroz con tofu y verduras',['arroz','tofu','calabacín']],['Ternera con patata y ensalada',['ternera','patata','lechuga']],['Tortilla de patata y ensalada',['huevo','patata','lechuga']],['Garbanzos con espinacas y arroz',['garbanzos','espinacas','arroz']],['Pescado blanco con quinoa y calabacín',['pescado blanco','quinoa','calabacín']]],
 merienda:[
 ['Fruta de temporada y yogur natural',['fruta de temporada','yogur natural']],['Pera con nueces',['pera','nueces']],['Tostada integral con queso fresco',['pan integral','queso fresco']],['Manzana con semillas',['manzana','semillas']],['Plátano y yogur natural',['plátano','yogur natural']],['Zanahoria con hummus',['zanahoria','garbanzos']],['Frutos rojos y yogur natural',['frutos rojos','yogur natural']],['Mandarina con almendras',['mandarina','almendras']]],
 cena:[
 ['Tortilla de verduras y ensalada',['huevo','calabacín','lechuga']],['Salmón al horno con verduras',['salmón','brócoli','zanahoria']],['Crema de calabaza con pollo',['calabaza','pollo']],['Ensalada de garbanzos y huevo',['garbanzos','huevo','tomate']],['Merluza con verduras asadas',['merluza','calabacín','pimiento']],['Tofu salteado con arroz y verduras',['tofu','arroz','brócoli']],['Sopa de verduras y tortilla',['zanahoria','calabacín','huevo']],['Pollo con ensalada y patata',['pollo','lechuga','patata']],['Pescado blanco con boniato y espinacas',['pescado blanco','boniato','espinacas']],['Alubias con verduras al horno',['alubias','pimiento','calabacín']],['Pavo con arroz y ensalada',['pavo','arroz','lechuga']],['Revuelto de champiñones y espinacas',['huevo','champiñones','espinacas']],['Lentejas suaves con verduras',['lentejas','zanahoria','calabacín']],['Quinoa con pollo y verduras',['quinoa','pollo','brócoli']]]
};
const aliases={lactosa:['leche','yogur','queso'],lácteos:['leche','yogur','queso'],leche:['leche','yogur','queso'],gluten:['pan','pasta','cuscús'],trigo:['pan','pasta','cuscús'],huevo:['huevo','tortilla'],pescado:['salmón','merluza','pescado','atún'],marisco:['marisco'],'frutos secos':['nueces','almendras'],soja:['tofu'],legumbres:['lentejas','garbanzos','alubias'],vegetariana:['pollo','pavo','ternera','salmón','merluza','pescado','atún'],vegana:['pollo','pavo','ternera','salmón','merluza','pescado','atún','huevo','yogur','queso']};
function fold(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()}
function exclusions(p){const terms=fold([p.allergies,p.avoid].join(',')).split(/[,;\n]+/).map(x=>x.trim()).filter(Boolean);const prefs=fold(p.preferences);for(const key of ['vegetariana','vegana'])if(prefs.includes(key))terms.push(key);const blocked=new Set();for(const term of terms){const key=Object.keys(aliases).find(k=>fold(k)===term);if(key)aliases[key].forEach(x=>blocked.add(fold(x)));else blocked.add(term)}return [...blocked]}
function generate(p,days=7,variation=0){const blocked=exclusions(p);const result=[];for(let day=0;day<days;day++){const meals={};for(const [slot,options] of Object.entries(recipes)){const available=options.filter(r=>!r[1].some(ingredient=>blocked.some(term=>fold(ingredient).includes(term)||fold(r[0]).includes(term))));if(!available.length)return {days:[],error:'No hay suficientes recetas seguras para '+slot+'. Revisa las restricciones con un profesional antes de crear un menú.'};const index=(day+variation*3+Math.floor(day/available.length))%available.length;const recipe=available[index];meals[slot]={name:recipe[0],ingredients:recipe[1]}}result.push(meals)}return {days:result,error:null}}
function shopping(days,start=0,end=days.length,diners=1){const counts=new Map();for(const day of days.slice(start,end))for(const meal of Object.values(day))for(const ingredient of meal.ingredients)counts.set(ingredient,(counts.get(ingredient)||0)+Math.max(1,Number(diners)||1));return [...counts].sort((a,b)=>a[0].localeCompare(b[0],'es'))}
return {generate,shopping,exclusions};
});
