(function(){
const STORAGE='stannet.nutriia.v1';
const seed={users:{},session:null};
const read=()=>{try{return JSON.parse(localStorage.getItem(STORAGE))||structuredClone(seed)}catch{return structuredClone(seed)}};
const write=(state)=>localStorage.setItem(STORAGE,JSON.stringify(state));
let state=read(), currentUser=state.session, currentProfileId=null;
const $=(s)=>document.querySelector(s);
const panels=['dashboard','profile','nutrition','training','pantry','recovery','beast'];
const today=()=>new Date().toISOString().slice(0,10);
const baseProfile=(name='Perfil principal')=>({id:crypto.randomUUID(),name,height:175,weight:78,goal:'recomposicion',activity:'media',preferences:'mediterranea, alta en proteina',allergies:'',avoid:'',diners:1,budget:65,favorites:['pollo','huevos','yogur griego'],pantry:['arroz','avena','atun','verduras congeladas'],history:{},limits:'',equipment:'mancuernas, banco, bandas',sleepGoal:7.5,supplements:'proteina, creatina',music:'https://www.youtube.com/embed/videoseries?list=PL4fGSI1pDJn5kI81J1fYWK5eZRl1zJ5kM'});
const plans={meals:[['Desayuno','Avena con yogur griego, frutos rojos y nueces','Avena 60 g, yogur 200 g, frutos rojos 100 g, nueces 15 g'],['Comida','Bowl de pollo, arroz y verduras','Pollo 180 g, arroz 80 g en seco, verduras 250 g, aceite 10 g'],['Merienda','Tostada proteica','Pan integral 80 g, queso fresco 100 g, tomate, pavo 80 g'],['Cena','Salmón con patata y ensalada','Salmon 170 g, patata 280 g, ensalada grande']],exercises:[['Sentadilla goblet','3 series x 8-10 repeticiones','Descanso 90 s','Carga conservadora: deja 3 repeticiones en recamara. RPE 6-7.'],['Press con mancuernas','3 x 8-12','Descanso 90 s','Escapulas estables, recorrido controlado y sin dolor.'],['Remo con mancuerna','3 x 10-12 por lado','Descanso 75 s','Espalda neutra, tira con el codo, pausa arriba.'],['Peso muerto rumano','2 x 8-10','Descanso 120 s','Bisagra de cadera, columna neutra, RPE maximo 7 si eres principiante.'],['Plancha','3 x 30-45 s','Descanso 60 s','Respira, pelvis neutra, corta la serie si pierdes tecnica.']]};
function user(){return currentUser?state.users[currentUser]:null}
function profile(){const u=user();return u?.profiles.find(p=>p.id===currentProfileId)||u?.profiles[0]}
function saveProfile(p){const u=user();const i=u.profiles.findIndex(x=>x.id===p.id);u.profiles[i]=p;write(state);renderAll()}
function score(p){const h=p.history[today()]||{};let done=0;['meals','training','sleep','supplements'].forEach(k=>{if(h[k])done++});return Math.round(done/4*100)}
function log(key,val=true){const p=profile();p.history[today()]={...(p.history[today()]||{}),[key]:val};saveProfile(p)}
function renderAuth(){const logged=!!user();$('#authCard').classList.toggle('hidden',logged);$('#profileCard').classList.toggle('hidden',!logged);if(logged){const sel=$('#profileSelect');sel.innerHTML=user().profiles.map(p=>'<option value="'+p.id+'">'+p.name+'</option>').join('');currentProfileId=currentProfileId||user().profiles[0].id;sel.value=currentProfileId;}}
function gate(){if(!user())return '<div class="empty-state"><h3>Inicia sesion para activar Nutri IA</h3><p>Crearas un espacio local con perfiles, historial y seguimiento privado en este navegador.</p></div>';return null}
function head(t,p){return '<div class="panel-head"><div><p class="eyebrow">Nutri IA by StanNet</p><h2>'+t+'</h2></div><p>'+p+'</p></div>'}
function renderDashboard(){const g=gate();if(g){$('#dashboard').innerHTML=g;return}const p=profile(), h=p.history[today()]||{}, s=score(p);$('#heroScore').textContent=s+'%';$('#dashboard').innerHTML=head('Dashboard diario','Resumen accionable para comer, entrenar, descansar y registrar el dia sin ruido.')+'<div class="grid-3"><article class="metric-card"><span>Constancia hoy</span><strong>'+s+'%</strong><div class="progress-bar"><span style="width:'+s+'%"></span></div></article><article class="metric-card"><span>Peso / altura</span><strong>'+p.weight+' kg</strong><p>'+p.height+' cm · objetivo '+p.goal+'</p></article><article class="metric-card"><span>Presupuesto semanal</span><strong>'+p.budget+' €</strong><p>'+p.diners+' comensal(es)</p></article></div><div class="grid-2" style="margin-top:14px"><article class="module-card"><h3>Checklist de hoy</h3>'+['meals:Menu completado','training:Entreno realizado','sleep:Sueño registrado','supplements:Suplementos revisados'].map(x=>{const [k,l]=x.split(':');return '<label class="check-row"><input type="checkbox" data-log="'+k+'" '+(h[k]?'checked':'')+'> '+l+'</label>'}).join('')+'</article><article class="module-card"><h3>Alertas inteligentes</h3><p class="safe-note">'+alerts(p).join('<br>')+'</p></article></div>'}
function alerts(p){let a=[];if(p.allergies)a.push('Alergias/intolerancias activas: revisa etiquetas y contaminacion cruzada.');if(p.limits)a.push('Limitaciones o lesion: evita dolor, reduce carga y consulta a un profesional.');if(p.supplements)a.push('Suplementos: confirma dosis, interacciones y contraindicaciones con personal sanitario.');return a.length?a:['Sin alertas criticas configuradas. Mantener progresion gradual.']}
function renderProfile(){const g=gate();if(g){$('#profile').innerHTML=g;return}const p=profile();$('#profile').innerHTML=head('Onboarding y datos','Actualiza datos personales, objetivos, preferencias y restricciones. Nutri IA recalcula el panel al guardar.')+'<form class="module-card form-stack" id="profileForm"><div class="inline-fields"><div><label>Nombre</label><input name="name" value="'+p.name+'"></div><div><label>Altura cm</label><input name="height" type="number" value="'+p.height+'"></div><div><label>Peso kg</label><input name="weight" type="number" step="0.1" value="'+p.weight+'"></div></div><div class="inline-fields"><div><label>Objetivo</label><select name="goal"><option>recomposicion</option><option>perdida de grasa</option><option>ganancia muscular</option><option>mantenimiento</option></select></div><div><label>Actividad</label><select name="activity"><option>baja</option><option>media</option><option>alta</option></select></div><div><label>Comensales</label><input name="diners" type="number" min="1" value="'+p.diners+'"></div></div><label>Preferencias</label><textarea name="preferences">'+p.preferences+'</textarea><label>Alergias o intolerancias</label><textarea name="allergies">'+p.allergies+'</textarea><label>Alimentos a evitar</label><textarea name="avoid">'+p.avoid+'</textarea><div class="inline-fields"><div><label>Presupuesto semanal €</label><input name="budget" type="number" value="'+p.budget+'"></div><div><label>Material entrenamiento</label><input name="equipment" value="'+p.equipment+'"></div><div><label>Limitaciones</label><input name="limits" value="'+p.limits+'"></div></div><button class="button primary" type="submit">Guardar perfil <span>✓</span></button></form>';$('[name=goal]').value=p.goal;$('[name=activity]').value=p.activity}
function renderNutrition(){const g=gate();if(g){$('#nutrition').innerHTML=g;return}const p=profile();const avoid=(p.avoid+','+p.allergies).toLowerCase();const meals=plans.meals.filter(m=>!avoid||!avoid.split(',').some(a=>a.trim()&&m.join(' ').toLowerCase().includes(a.trim())));$('#nutrition').innerHTML=head('Nutricion personalizada','Menu diario/semanal con cantidades, recetas, compra y control simple de repeticiones.')+'<div class="chip-list">'+p.favorites.map(f=>'<span class="chip">Favorito: '+f+'</span>').join('')+'</div><div class="grid-2" style="margin-top:14px">'+meals.map((m,i)=>'<article class="meal-card"><span>Dia '+(i+1)+' · '+p.goal+'</span><h3>'+m[0]+'</h3><p>'+m[1]+'</p><ul><li>'+m[2]+'</li><li>Ajusta cantidades si hambre, rendimiento o peso cambian durante 2 semanas.</li></ul></article>').join('')+'</div><article class="module-card" style="margin-top:14px"><h3>Lista de compra sugerida</h3><p>'+shopping(p).join(' · ')+'</p><button class="button small ghost" data-log="meals" type="button">Marcar menu de hoy completado</button></article>'}
function shopping(p){return ['proteina magra','huevos','yogur griego','arroz o patata','verduras','fruta','aceite de oliva','frutos secos'].filter(x=>!(p.avoid||'').toLowerCase().includes(x))}
function renderTraining(){const g=gate();if(g){$('#training').innerHTML=g;return}const p=profile(), h=p.history[today()]||{};$('#training').innerHTML=head('Entrenamiento adaptativo','Carga conservadora, tecnica clara, RPE 1-10, progresion y registro diario por ejercicio.')+'<div class="grid-2">'+plans.exercises.map((e,i)=>'<article class="exercise-card"><span>'+e[1]+' · '+e[2]+'</span><h3>'+e[0]+'</h3><p>'+e[3]+'</p><label class="check-row"><input type="checkbox" data-ex="'+i+'" '+(h['ex'+i]?'checked':'')+'> Realizado hoy</label><div class="exercise-log"><input placeholder="kg" data-field="kg'+i+'" value="'+(h['kg'+i]||'')+'"><input placeholder="reps" data-field="reps'+i+'" value="'+(h['reps'+i]||'')+'"><input placeholder="RPE 1-10" data-field="rpe'+i+'" value="'+(h['rpe'+i]||'')+'"><input placeholder="nota" data-field="note'+i+'" value="'+(h['note'+i]||'')+'"></div></article>').join('')+'</div><article class="module-card" style="margin-top:14px"><h3>Video tecnica</h3><iframe class="video-frame" src="https://www.youtube.com/embed/aclHkVaku9U" title="Video de tecnica de sentadilla" allowfullscreen></iframe><p class="safe-note">Si aparece dolor agudo, mareo o perdida de tecnica, detente y consulta con un profesional.</p></article>'}
function renderPantry(){const g=gate();if(g){$('#pantry').innerHTML=g;return}const p=profile();$('#pantry').innerHTML=head('Despensa e inventario','Controla lo que ya tienes, reduce compras repetidas y evita alimentos no deseados.')+'<article class="module-card"><form id="pantryForm" class="form-stack"><label>Despensa, separados por coma</label><textarea name="pantry">'+p.pantry.join(', ')+'</textarea><label>Favoritos, separados por coma</label><textarea name="favorites">'+p.favorites.join(', ')+'</textarea><button class="button primary" type="submit">Actualizar despensa <span>✓</span></button></form></article><div class="grid-3" style="margin-top:14px">'+p.pantry.map(i=>'<article class="metric-card"><span>En casa</span><strong style="font-size:22px">'+i+'</strong></article>').join('')+'</div>'}
function renderRecovery(){const g=gate();if(g){$('#recovery').innerHTML=g;return}const p=profile();$('#recovery').innerHTML=head('Sueño y suplementos','Registro sencillo para recuperar mejor y revisar suplementos con prudencia.')+'<div class="grid-2"><article class="module-card"><h3>Sueño</h3><label>Objetivo de horas</label><input id="sleepGoal" type="number" step=".5" value="'+p.sleepGoal+'"><button class="button small ghost" data-log="sleep" type="button">Registrar sueño de hoy</button></article><article class="module-card"><h3>Suplementos</h3><textarea id="supplements">'+p.supplements+'</textarea><p class="safe-note">No mezcles suplementos con medicacion sin revision profesional. Evita promesas de curacion o diagnostico.</p><button class="button small ghost" data-log="supplements" type="button">Revisado hoy</button></article></div>'}
function renderBeast(){const g=gate();if(g){$('#beast').innerHTML=g;return}const p=profile();$('#beast').innerHTML=head('Modo Bestia','Sesion de foco para entrenar: musica, intensidad controlada y registro sin excusas.')+'<article class="module-card beast-on"><h3>Activacion</h3><p>Calienta 8 minutos, usa RPE 6-8, tecnica limpia y progresion pequeña. Bestia no significa imprudente.</p><iframe class="video-frame" src="'+p.music+'" title="Musica de entrenamiento" allow="autoplay; encrypted-media" allowfullscreen></iframe><button class="button primary" data-log="training" type="button">Entreno completado <span>✓</span></button></article>'}
function renderAll(){renderAuth();renderDashboard();renderProfile();renderNutrition();renderTraining();renderPantry();renderRecovery();renderBeast()}
$('#loginForm').addEventListener('submit',e=>{e.preventDefault();const email=$('#email').value.trim().toLowerCase(),pin=$('#pin').value;if(pin.length<4)return alert('El PIN debe tener al menos 4 digitos.');if(!state.users[email])state.users[email]={pinHash:btoa(pin).slice(0,24),profiles:[baseProfile()]};state.session=email;currentUser=email;currentProfileId=state.users[email].profiles[0].id;write(state);renderAll()});
$('#profileSelect').addEventListener('change',e=>{currentProfileId=e.target.value;renderAll()});
$('#addProfile').addEventListener('click',()=>{const u=user();const p=baseProfile('Perfil '+(u.profiles.length+1));u.profiles.push(p);currentProfileId=p.id;write(state);renderAll()});
$('#logout').addEventListener('click',()=>{state.session=null;currentUser=null;currentProfileId=null;write(state);renderAll()});
document.addEventListener('click',e=>{const tab=e.target.closest('[data-tab]');if(tab){document.querySelectorAll('.app-tabs button').forEach(b=>b.classList.remove('active'));tab.classList.add('active');panels.forEach(id=>$('#'+id).classList.toggle('active',id===tab.dataset.tab));}const lg=e.target.closest('[data-log]');if(lg)log(lg.dataset.log,true);if(e.target.matches('[data-start]'))document.querySelector('.nutri-shell').scrollIntoView({behavior:'smooth'});if(e.target.matches('[data-demo]')){state.users.demo={pinHash:'demo',profiles:[baseProfile('Demo StanNet')]};state.session='demo';currentUser='demo';currentProfileId=state.users.demo.profiles[0].id;write(state);renderAll();}});
document.addEventListener('change',e=>{if(e.target.matches('[data-ex]'))log('ex'+e.target.dataset.ex,e.target.checked);if(e.target.matches('[data-field]')){const p=profile();p.history[today()]={...(p.history[today()]||{}),[e.target.dataset.field]:e.target.value};saveProfile(p)}});
document.addEventListener('submit',e=>{if(e.target.id==='profileForm'){e.preventDefault();const p=profile(),fd=new FormData(e.target);['name','goal','activity','preferences','allergies','avoid','equipment','limits'].forEach(k=>p[k]=fd.get(k));['height','weight','diners','budget'].forEach(k=>p[k]=Number(fd.get(k)));saveProfile(p)}if(e.target.id==='pantryForm'){e.preventDefault();const p=profile(),fd=new FormData(e.target);p.pantry=fd.get('pantry').split(',').map(x=>x.trim()).filter(Boolean);p.favorites=fd.get('favorites').split(',').map(x=>x.trim()).filter(Boolean);saveProfile(p)}});
renderAll();
})();