(()=>{'use strict';
const L=window.stannetWebLessons||[];let current=0;const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
const lines=s=>esc(s).replace(/\n/g,'<br>');
function outline(){const groups={};L.forEach((l,i)=>(groups[l.track]??=[]).push({l,i}));$('web-outline').innerHTML=Object.entries(groups).map(([track,x])=>'<details '+(track===L[current]?.track?'open':'')+'><summary>'+esc(track)+' <span>'+x.length+' temas</span></summary><ol>'+x.map(({l,i})=>'<li><button class="pa-outline-link '+(i===current?'active':'')+'" data-i="'+i+'" '+(i===current?'aria-current="step"':'')+'>'+esc(l.id+' · '+l.title)+'</button></li>').join('')+'</ol></details>').join('')}
function list(){$('web-list').innerHTML='';outline()}
function navigation(){document.querySelectorAll('[data-web-step]').forEach(b=>{const next=b.dataset.webStep==='next';const target=L[current+(next?1:-1)];b.disabled=!target;b.textContent=target?(next?'Siguiente: ':'Anterior: ')+target.id+' · '+target.title:(next?'Fin del temario':'Inicio del temario')});document.querySelectorAll('[data-web-position]').forEach(el=>el.textContent='Lección '+(current+1)+' de '+L.length+' · '+L[current].track)}
function theory(l){const d=l.deep||{};const objectives=Array.isArray(d.objectives)?d.objectives:[];const sections=Array.isArray(d.sections)?d.sections:[];const concepts=Array.isArray(d.concepts)?d.concepts:[];const checklist=Array.isArray(d.checklist)?d.checklist:[];
let out='<article class="pa-theory-book"><section class="pa-theory-intro"><p class="case-kicker">TEORÍA · '+esc(l.id)+'</p><h3>Qué aprenderás</h3><p>'+lines(l.theory||'Lección práctica de '+l.title+'.')+'</p></section>';
if(objectives.length)out+='<section class="pa-deep-section"><h3>Objetivos</h3><ul>'+objectives.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul></section>';
if(concepts.length)out+='<section class="pa-deep-section"><h3>Conceptos de la lección</h3><ol>'+concepts.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ol></section>';
out+=sections.map(s=>'<section class="pa-deep-section"><h3>'+esc(s[0])+'</h3><p>'+lines(s[1])+'</p></section>').join('');
if(checklist.length)out+='<section class="pa-deep-section"><h3>Checklist de dominio</h3><ul>'+checklist.map(x=>'<li>□ '+esc(x)+'</li>').join('')+'</ul></section>';
return out+'</article>'}
function load(i){const l=L[i];if(!l)return;current=i;$('web-badge').textContent=l.track;$('web-title').textContent=l.id+' · '+l.title;$('web-theory').innerHTML=theory(l);$('web-challenge').textContent='Reto: '+l.challenge;$('web-editor').value=l.starter;$('web-preview').srcdoc='';$('web-grade').hidden=true;$('web-grade').innerHTML='';$('web-check').style.display=l.track==='JavaScript'?'':'none';list();navigation();document.querySelector('.pa-lab-main')?.scrollIntoView({behavior:'smooth',block:'start'})}
function grade(){const l=L[current],g=window.StanNetJSGrader&&window.StanNetJSGrader.grade(l,$('web-editor').value);if(!g)return;const p=$('web-grade');p.hidden=false;p.innerHTML='<p class="pa-grade-title">'+(g.ok?'✓ Ejercicio superado':'Todavía no. '+g.passed+' de '+g.total+' comprobaciones correctas')+'</p><ul class="pa-grade-list">'+g.results.map(r=>'<li class="pa-grade-item '+(r.pass?'pa-grade-pass':'pa-grade-fail')+'"><strong>'+(r.pass?'✓ ':'○ ')+esc(r.name)+'</strong>'+(r.pass?'':'<div class="pa-grade-hint">Pista: '+esc(r.hint)+'</div>')+'</li>').join('')+'</ul><div class="pa-grade-summary">'+(g.ok?'Dominio comprobado para este reto. Continúa cuando puedas explicar tu solución.':'Corrige únicamente los puntos pendientes y vuelve a comprobar.')+'</div>';if(g.ok){let x={};try{x=JSON.parse(localStorage.getItem('stannet-js-autograder-v1')||'{}')}catch(e){}x[l.id]={passed:true,at:new Date().toISOString()};localStorage.setItem('stannet-js-autograder-v1',JSON.stringify(x))}}
document.addEventListener('DOMContentLoaded',()=>{if(!L.length){$('web-theory').innerHTML='<p>No se pudo cargar el temario.</p>';return}$('web-list').onclick=e=>{const b=e.target.closest('[data-i]');if(b)load(+b.dataset.i)};$('web-outline').onclick=e=>{const b=e.target.closest('[data-i]');if(b)load(+b.dataset.i)};document.querySelectorAll('[data-web-step]').forEach(b=>b.addEventListener('click',()=>load(current+(b.dataset.webStep==='next'?1:-1))));$('preview-btn').onclick=()=>{$('web-preview').srcdoc=$('web-editor').value};$('web-check').onclick=grade;$('web-reset').onclick=()=>load(current);load(0)});
})();
