const assert = require('node:assert/strict');
const fs = require('node:fs');

const widget = fs.readFileSync('stannet-ai.js', 'utf8');
const worker = fs.readFileSync('worker.js', 'utf8');
const loader = fs.readFileSync('stannet-ai-loader.js', 'utf8');

assert.ok(widget.includes('window.SpeechRecognition||window.webkitSpeechRecognition'), 'Voice input must support standard and WebKit SpeechRecognition');
assert.match(loader, /ai\.src='\/stannet-ai\.js\?v=\d{8}-[a-z0-9]+'/i, 'Voice widget URL must be cache-busted');
assert.ok(widget.includes("recognition.lang=lastVoiceLang"), 'Voice input must follow the active conversation language');
assert.ok(widget.includes("detectVoiceLanguage"), 'Voice mode must detect Spanish and English turns');
assert.ok(widget.includes("'en-GB-SoniaNeural'"), 'StanNet AI must select an English neural voice when English is detected');
assert.ok(widget.includes("fetch('/api/speech'"), 'Assistant must use the protected Cloudflare TTS endpoint');
assert.ok(widget.includes("purpose:'chat'"), 'Assistant audio must be marked as dynamic chat content');
assert.ok(widget.includes('split(/[ \\t\\r\\n]+/)'), 'Speech replies must be chunked safely below the TTS payload limit');
assert.ok(widget.includes('aria-label="Activar conversación por voz"'), 'Voice controls must be accessible');
assert.ok(widget.includes('StanNet recibe la transcripción'), 'Voice processing disclosure must be visible');
assert.ok(widget.includes('Escuchar respuesta'), 'Text replies must be playable by browser users');
assert.ok(widget.includes("setActivity('interrupted')"), 'Voice conversation must expose an interrupted state for barge-in');
assert.ok(widget.includes('looksLikeSpeakerEcho'), 'Barge-in must filter likely speaker echo before accepting an interruption');
assert.ok(widget.includes("if(listenAfter&&voiceEnabled)startListening()"), 'Recognition must restart while the assistant is speaking so the user can interrupt');
assert.ok(widget.includes("voiceThinking&&!speechActive"), 'Listening must remain available during assistant speech without reopening it while the model is thinking');
assert.ok(widget.includes('INTERRUPTION_WORDS'), 'Short explicit interruption words must bypass speaker-echo filtering');
assert.ok(widget.includes("'para','espera','no','oye','stop','wait'"), 'Spanish and English short interruption vocabulary must be recognized');
assert.ok(widget.includes('speechActive?120:220'), 'Voice recognition restart delay must stay short during spoken turns');
assert.ok(widget.includes('speechActive&&!isExplicitInterruption(transcript)'), 'Speaker audio must not interrupt the agent unless the user gives an explicit interruption command');
assert.ok(widget.includes('di «para» o «espera»'), 'Voice UI must explain the safe interruption command while the agent is speaking');
assert.ok(widget.includes('listenAfter&&voiceEnabled&&!mobile.matches'), 'Live barge-in must stay enabled on desktop only');
assert.ok(widget.includes('mobile.matches&&recognitionRunning'), 'Mobile must stop recognition before playing assistant audio');
assert.ok(widget.includes('(mobile.matches&&speechActive)'), 'Mobile must not restart recognition while assistant speech is active');
assert.ok(widget.includes('volveré a escucharte al terminar'), 'Mobile voice status must explain half-duplex listening');
assert.ok(worker.includes("'es-ES': {"), 'Cloudflare speech endpoint must allow Spanish (Spain)');
assert.ok(worker.includes("'es-ES-ElviraNeural'") && worker.includes("'es-ES-AlvaroNeural'"), 'Spanish Neural voices must be allowlisted');
assert.ok(worker.includes("purpose === 'chat' ? 'no-store'"), 'Chat audio must not be cached publicly');
assert.ok(worker.includes("const conversational = purpose === 'chat'"), 'Chat TTS must use conversational prosody');
assert.ok(worker.includes('rate="-2%" pitch="+0st" volume="+0%"'), 'Chat TTS must avoid the old uniformly slow robotic cadence');
assert.ok(worker.includes('<break time="190ms"/>'), 'Chat TTS must include natural sentence pauses');
assert.ok(worker.includes('<break time="90ms"/>'), 'Chat TTS must include light punctuation pauses');

console.log('PASS: StanNet AI supports consent-based adaptive Spanish/English voice replies.');
