'use strict';
const assert=require('node:assert/strict');
const m=require('../../ayudaencasa/domain/model.cjs');
const client={userId:'client_1234567890',role:'client'};
const other={userId:'client_ABCDEFGHIJ',role:'client'};
const pro={userId:'professional_1234',role:'professional'};
const admin={userId:'admin_12345678901',role:'admin'};
const req={clientId:client.userId,status:'open'};
assert.equal(m.canManageRequest(client,req),true);
assert.equal(m.canManageRequest(other,req),false,'IDOR: another client must not manage the request');
assert.equal(m.canSubmitProposal(pro,req),true);
assert.equal(m.canSubmitProposal(client,req),false);
const conv={clientId:client.userId,professionalId:pro.userId};
assert.equal(m.canAccessConversation(client,conv),true);
assert.equal(m.canAccessConversation(pro,conv),true);
assert.equal(m.canAccessConversation(other,conv),false,'IDOR: non-participant must not access chat');
assert.equal(m.canAccessConversation(admin,conv),true);
assert.throws(()=>m.assertText('<x>',{field:'body',min:1,max:2}),/Invalid body/);
console.log('AyudaEnCasa domain authorization tests passed');
