-- AyudaEnCasa schema reference
-- The executable source of truth is migrations/ayudaencasa/0001_core.sql through 0009_service_area.sql.
-- Do not apply this documentation file directly to production.
--
-- Domain tables created by the migrations:
-- aec_users
-- aec_categories
-- aec_professional_profiles
-- aec_professional_services
-- aec_requests
-- aec_proposals
-- aec_jobs
-- aec_reviews
-- aec_audit_events
-- aec_sessions
-- aec_auth_tokens
-- aec_login_events
-- aec_password_credentials
-- aec_rate_limits
-- aec_conversations
-- aec_conversation_participants
-- aec_messages
-- aec_reports
-- aec_blocks
-- aec_privacy_requests
-- aec_notification_outbox
-- aec_entitlements
-- aec_message_reads
--
-- Rebuild a database by applying the numbered migrations in ascending order.
PRAGMA foreign_keys = ON;
